services:
  - type: web
    name: balmores-structural-backend
    runtime: python
    plan: free
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.14"
    buildCommand: pip install --no-cache-dir -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: balmores-structural-frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
