import type { FeaPromptResponse } from "@/lib/api";

function fmt(n: number, d = 4): string {
  return Number.isFinite(n) ? n.toFixed(d) : "0";
}

/** Map Balmores support labels to ETABS joint restraint flags (U1..U3, R1..R3). */
function restraintFlags(kind: string): string {
  const k = (kind || "pin").toLowerCase();
  if (k === "fixed") return "Yes Yes Yes Yes Yes Yes";
  if (k === "roller") return "No Yes Yes Yes Yes No";
  if (k === "free") return "No No No No No No";
  return "Yes Yes Yes Yes Yes No";
}

function ulsCombo(res: FeaPromptResponse): string {
  const combo = res.load_combination.replace(/\+/g, " +").trim();
  return combo || "1.2DEAD + 1.6LIVE";
}

function appendBeamLoads(lines: string[], res: FeaPromptResponse): void {
  const pm = res.parsed_model;
  if (!pm || res.analysis_type !== "beam_2d") return;
  const members = res.geometry.members;
  if (!members.length) return;
  const frameId = members[0].id;
  const dl = pm.dl_kN_per_m ?? 0;
  const ll = pm.ll_kN_per_m ?? 0;
  const wu = 1.2 * dl + 1.6 * ll;
  if (wu > 0) {
    lines.push('TABLE:  "FRAME LOADS - DISTRIBUTED"');
    lines.push("   Frame=Frame   LoadPat=LoadPat   Direction=Direction   DistType=DistType   ForceA=ForceA   ForceB=ForceB   RelDistA=RelDistA   RelDistB=RelDistB");
    lines.push(`   ${frameId}   DEAD   Gravity   Force   ${fmt(-dl, 3)}   ${fmt(-dl, 3)}   0   1`);
    lines.push(`   ${frameId}   LIVE   Gravity   Force   ${fmt(-ll, 3)}   ${fmt(-ll, 3)}   0   1`);
    lines.push(`   ${frameId}   ULS1   Gravity   Force   ${fmt(-wu, 3)}   ${fmt(-wu, 3)}   0   1`);
    lines.push("");
  }
  const pointLoads = pm.point_loads ?? [];
  if (pointLoads.length) {
    lines.push('TABLE:  "FRAME LOADS - POINT"');
    lines.push("   Frame=Frame   LoadPat=LoadPat   Direction=Direction   RelDist=RelDist   Force=Force");
    const span = pm.span_m ?? 1;
    for (const pl of pointLoads) {
      const rel = span > 0 ? Math.min(1, Math.max(0, pl.x_m / span)) : 0.5;
      const caseName = (pl.case || "LIVE").toUpperCase().includes("DEAD") ? "DEAD" : "LIVE";
      lines.push(`   ${frameId}   ${caseName}   Gravity   ${fmt(rel, 4)}   ${fmt(-Math.abs(pl.P_kN), 3)}`);
    }
    lines.push("");
  }
}

function appendBuildingStories(lines: string[], res: FeaPromptResponse): void {
  if (res.analysis_type !== "building_3d") return;
  const heights = res.parsed_model?.story_heights_m;
  if (!heights?.length) return;
  lines.push('TABLE:  "STORY DEFINITIONS"');
  lines.push("   Story=Story   Height=Height");
  for (let i = 0; i < heights.length; i++) {
    lines.push(`   ${i + 1}   ${fmt(heights[i], 3)}`);
  }
  lines.push("");
}

/**
 * Build a CSI ETABS-compatible .e2k text file from a PyNite FEA result so the
 * user can import it via File → Import → ETABS (.e2k).
 */
export function buildFeaE2k(res: FeaPromptResponse): string {
  const meta = res.geometry.meta ?? {};
  const pm = res.parsed_model;
  const bw = pm?.beam_width_m ?? 0.3;
  const bd = pm?.beam_depth_m ?? 0.6;
  const cw = pm?.column_width_m ?? 0.45;
  const title = `Balmores_${res.analysis_type}_${res.load_combination}`.replace(/[^\w.-]+/g, "_").slice(0, 72);
  const lines: string[] = [];

  lines.push(`$ File ${title}.e2k`);
  lines.push("$ Program ETABS");
  lines.push("$ Generated by Balmores Structural — import via File → Import → ETABS (.e2k)");
  lines.push("$ Verify member demands and reactions against PyNite tables in the web report.");
  lines.push("");
  lines.push('TABLE:  "PROGRAM CONTROL"');
  lines.push("   PROGRAM=ETABS");
  lines.push("   VERSION=21.2.0");
  lines.push("");
  lines.push('TABLE:  "CONTROL - GENERAL UNITS"');
  lines.push("   FORCE=kN   LENGTH=m   TEMP=C");
  lines.push("");
  lines.push('TABLE:  "CONTROL - ACTIVE DEGREES OF FREEDOM"');
  lines.push("   UX=Yes UY=Yes UZ=Yes RX=Yes RY=Yes RZ=Yes");
  lines.push("");
  appendBuildingStories(lines, res);
  lines.push('TABLE:  "MATERIAL PROPERTIES 01 - GENERAL"');
  lines.push("   CONC1   Isotropic   Concrete   30000");
  lines.push("   STEEL1  Isotropic   Steel      200000");
  lines.push("");
  lines.push('TABLE:  "FRAME SECTION PROPERTIES 01 - GENERAL"');
  lines.push(
    `   BSEC1   Concrete   Rectangular   ${fmt(bw, 3)}   ${fmt(bd, 3)}   CONC1`,
  );
  lines.push(
    `   CSEC1   Concrete   Rectangular   ${fmt(cw, 3)}   ${fmt(cw, 3)}   CONC1`,
  );
  lines.push("");
  lines.push('TABLE:  "JOINT COORDINATES"');
  lines.push("   Joint=Joint   CoordSys=CoordSys   CoordType=CoordType   XorR=XorR   Y=Y   Z=Z   SpecialJt=SpecialJt");
  for (const n of res.geometry.nodes) {
    lines.push(`   ${n.id}   GLOBAL   Cartesian   ${fmt(n.x)}   ${fmt(n.y)}   ${fmt(n.z)}   No`);
  }
  lines.push("");
  lines.push('TABLE:  "CONNECTIVITY - FRAME"');
  lines.push("   Frame=Frame   JointI=JointI   JointJ=JointJ");
  for (const m of res.geometry.members) {
    lines.push(`   ${m.id}   ${m.start}   ${m.end}`);
  }
  lines.push("");
  lines.push('TABLE:  "FRAME SECTION ASSIGNMENTS"');
  lines.push("   Frame=Frame   SectionType=SectionType   AutoSelect=AutoSelect   AnalySect=AnalySect   DesignSect=DesignSect");
  for (const m of res.geometry.members) {
    const sec = m.kind === "column" ? "CSEC1" : "BSEC1";
    lines.push(`   ${m.id}   ${sec}   No   ${sec}   ${sec}`);
  }
  lines.push("");
  lines.push('TABLE:  "JOINT RESTRAINT ASSIGNMENTS"');
  lines.push("   Joint=Joint   U1=U1   U2=U2   U3=U3   R1=R1   R2=R2   R3=R3");
  const supportKinds = (meta.support_kinds as string[] | undefined) ?? [];
  const supportNodes = (meta.support_node_ids as string[] | undefined) ?? [];
  if (supportNodes.length && supportKinds.length) {
    for (let i = 0; i < supportNodes.length; i++) {
      lines.push(`   ${supportNodes[i]}   ${restraintFlags(supportKinds[i] ?? "pin")}`);
    }
  } else if (res.analysis_type === "building_3d") {
    for (const n of res.geometry.nodes) {
      if (Math.abs(n.z) < 1e-6) {
        lines.push(`   ${n.id}   Yes Yes Yes Yes Yes Yes`);
      }
    }
  } else {
    const left = res.geometry.nodes[0]?.id;
    const right = res.geometry.nodes[res.geometry.nodes.length - 1]?.id;
    if (left) lines.push(`   ${left}   ${restraintFlags("pin")}`);
    if (right && right !== left) lines.push(`   ${right}   ${restraintFlags("roller")}`);
  }
  lines.push("");
  lines.push('TABLE:  "LOAD PATTERN DEFINITIONS"');
  lines.push("   LoadPat=LoadPat   DesignType=DesignType   SelfWtMult=SelfWtMult");
  lines.push("   DEAD   Dead   0");
  lines.push("   LIVE   Live   0");
  if (res.design_criteria?.wind?.pressure_kpa) {
    lines.push("   WIND   Wind   0");
  }
  lines.push("");
  lines.push('TABLE:  "LOAD CASE DEFINITIONS"');
  lines.push("   Case=Case   Type=Type   InitialCond=InitialCond");
  lines.push("   DEAD   LinStatic   Zero");
  lines.push("   LIVE   LinStatic   Zero");
  lines.push("");
  lines.push('TABLE:  "LOAD COMBINATION DEFINITIONS"');
  lines.push("   Combo=Combo   ComboType=ComboType   AutoDesign=AutoDesign   CaseName=CaseName   ScaleFactor=ScaleFactor");
  lines.push(`   ULS1   Linear Add   No   ${ulsCombo(res)}   Strength`);
  lines.push("");
  appendBeamLoads(lines, res);
  if (res.analysis_type === "building_3d") {
    const dl = pm?.dl_kpa ?? 0;
    const ll = pm?.ll_kpa ?? 0;
    if (dl > 0 || ll > 0) {
      lines.push("$ Floor DL/LL (kPa) — assign in ETABS area loads to match PyNite tributary conversion:");
      lines.push(`$   DEAD floor pressure ≈ ${fmt(dl, 2)} kPa`);
      lines.push(`$   LIVE floor pressure ≈ ${fmt(ll, 2)} kPa`);
      lines.push("");
    }
  }
  lines.push("$ Balmores interpreted brief (reference only — not imported as loads)");
  for (const line of res.input_summary.replace(/\*\*/g, "").split("\n")) {
    if (line.trim()) lines.push(`$ ${line.trim()}`);
  }
  lines.push("");
  lines.push("$ PyNite governing envelopes (reference for ETABS cross-check)");
  for (const card of res.result_cards.slice(0, 12)) {
    lines.push(`$   ${card.label}: ${card.value}${card.unit ? " " + card.unit : ""}`);
  }
  lines.push("");
  lines.push("END TABLE DATA");
  lines.push("$ END OF MODEL FILE");
  return lines.join("\n");
}

export function downloadFeaE2k(res: FeaPromptResponse) {
  const base = `balmores_${res.analysis_type}_${Date.now()}`;
  const blob = new Blob([buildFeaE2k(res)], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${base}.e2k`;
  a.rel = "noopener";
  a.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 30_000);
}
