import type { FeaPromptResponse } from "@/lib/api";

function fmt(n: number, d = 4): string {
  return Number.isFinite(n) ? n.toFixed(d) : "0";
}

/** Map Balmores support labels to ETABS joint restraint flags (U1..U3, R1..R3). */
function restraintFlags(kind: string): string {
  const k = (kind || "pin").toLowerCase();
  if (k === "fixed") return "Yes Yes Yes Yes Yes Yes";
  if (k === "roller") return "No Yes Yes Yes Yes No";
  if (k === "free") return "No No No No No No";
  return "Yes Yes Yes Yes Yes No";
}

/**
 * Build a CSI ETABS-compatible .e2k text file from a PyNite FEA result so the
 * user can import it via File → Import → ETABS (.e2k).
 */
export function buildFeaE2k(res: FeaPromptResponse): string {
  const meta = res.geometry.meta ?? {};
  const pm = res.parsed_model;
  const bw = pm?.beam_width_m ?? 0.3;
  const bd = pm?.beam_depth_m ?? 0.6;
  const cw = pm?.column_width_m ?? 0.45;
  const title = `Balmores ${res.analysis_type} ${res.load_combination}`.slice(0, 72);
  const lines: string[] = [];

  lines.push(`$ File ${title}.e2k`);
  lines.push("$ Program ETABS");
  lines.push("$ Generated by Balmores Structural — import via File → Import → ETABS (.e2k)");
  lines.push("");
  lines.push('TABLE:  "PROGRAM CONTROL"');
  lines.push("   PROGRAM=ETABS");
  lines.push("");
  lines.push('TABLE:  "CONTROL - GENERAL UNITS"');
  lines.push("   FORCE=kN   LENGTH=m   TEMP=C");
  lines.push("");
  lines.push('TABLE:  "CONTROL - ACTIVE DEGREES OF FREEDOM"');
  lines.push("   UX=Yes UY=Yes UZ=Yes RX=Yes RY=Yes RZ=Yes");
  lines.push("");
  lines.push('TABLE:  "MATERIAL PROPERTIES 01 - GENERAL"');
  lines.push("   CONC1   Isotropic   Concrete   30000");
  lines.push("   STEEL1  Isotropic   Steel      200000");
  lines.push("");
  lines.push('TABLE:  "FRAME SECTION PROPERTIES 01 - GENERAL"');
  lines.push(
    `   BSEC1   Concrete   Rectangular   ${fmt(bw, 3)}   ${fmt(bd, 3)}   CONC1`,
  );
  lines.push(
    `   CSEC1   Concrete   Rectangular   ${fmt(cw, 3)}   ${fmt(cw, 3)}   CONC1`,
  );
  lines.push("");
  lines.push('TABLE:  "JOINT COORDINATES"');
  for (const n of res.geometry.nodes) {
    lines.push(`   ${n.id}   ${fmt(n.x)}   ${fmt(n.y)}   ${fmt(n.z)}`);
  }
  lines.push("");
  lines.push('TABLE:  "CONNECTIVITY - FRAME"');
  for (const m of res.geometry.members) {
    lines.push(`   ${m.id}   ${m.start}   ${m.end}`);
  }
  lines.push("");
  lines.push('TABLE:  "FRAME SECTION ASSIGNMENTS"');
  for (const m of res.geometry.members) {
    const sec = m.kind === "column" ? "CSEC1" : "BSEC1";
    lines.push(`   ${m.id}   ${sec}`);
  }
  lines.push("");
  lines.push('TABLE:  "JOINT RESTRAINT ASSIGNMENTS"');
  const supportKinds = (meta.support_kinds as string[] | undefined) ?? [];
  const supportNodes = (meta.support_node_ids as string[] | undefined) ?? [];
  if (supportNodes.length && supportKinds.length) {
    for (let i = 0; i < supportNodes.length; i++) {
      lines.push(`   ${supportNodes[i]}   ${restraintFlags(supportKinds[i] ?? "pin")}`);
    }
  } else if (res.analysis_type === "building_3d") {
    for (const n of res.geometry.nodes) {
      if (Math.abs(n.z) < 1e-6) {
        lines.push(`   ${n.id}   Yes Yes Yes Yes Yes Yes`);
      }
    }
  } else {
    const left = res.geometry.nodes[0]?.id;
    const right = res.geometry.nodes[res.geometry.nodes.length - 1]?.id;
    if (left) lines.push(`   ${left}   ${restraintFlags("pin")}`);
    if (right && right !== left) lines.push(`   ${right}   ${restraintFlags("roller")}`);
  }
  lines.push("");
  lines.push('TABLE:  "LOAD PATTERN DEFINITIONS"');
  lines.push("   DEAD   Dead");
  lines.push("   LIVE   Live");
  if (res.design_criteria?.wind?.pressure_kpa) {
    lines.push("   WIND   Wind");
  }
  lines.push("");
  lines.push('TABLE:  "LOAD CASE DEFINITIONS"');
  lines.push("   DEAD   Dead   LinStatic");
  lines.push("   LIVE   Live   LinStatic");
  lines.push("");
  lines.push('TABLE:  "LOAD COMBINATION DEFINITIONS"');
  const combo = res.load_combination.replace(/\+/g, " +").trim();
  lines.push(`   ULS1   ${combo || "1.2DEAD + 1.6LIVE"}   Strength`);
  lines.push("");
  lines.push("$ Balmores interpreted brief (reference only — not imported as loads)");
  for (const line of res.input_summary.replace(/\*\*/g, "").split("\n")) {
    if (line.trim()) lines.push(`$ ${line.trim()}`);
  }
  lines.push("");
  lines.push("$ Verify member demands and reactions against PyNite tables in the web report.");
  lines.push("END TABLE DATA");
  return lines.join("\n");
}

export function downloadFeaE2k(res: FeaPromptResponse) {
  const base = `balmores_${res.analysis_type}_${Date.now()}`;
  const blob = new Blob([buildFeaE2k(res)], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${base}.e2k`;
  a.rel = "noopener";
  a.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 30_000);
}
